[package]
name = "alexanderlindholt/tweenplus"
version = "2.13.3"
description = "An open-source tweening library for Roblox, featuring advanced datatypes, customization, interpolation, and optimization."
keywords = ["tween", "animation", "interpolation", "oklab", "performance", "optimization", "easing", "efficient", "networking"]
authors = ["Alexander Lindholt"]
license = "MIT"

realm = "shared"

registry = "https://github.com/upliftgames/wally-index"
repository = "https://github.com/AlexanderLindholt/TweenPlus"

[dependencies]
signalplus = "alexanderlindholt/signalplus@3.7.2"